### ISSUE TITLE
[BUG] 工单回复的如果是网址。 会有问题。无法回复！工单直接不见了

### ISSUE THREAD

**Issue by imrelax** [cedar2025/Xboard#104]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非XBoard问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-XBoard issues please go to the project side to ask questions

The XBoard version number you are using
当前使用的XBoard版本号
--------

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
工单如果回复的内容是网址或者带网址的内容。会 导致整个工单模块都变得不正常。 
不管是TG 回复。 还是在网页上回复。都一样。内容不能带网址。

或者说不能是网址开头的内容！

导致的问题就是。工单直接丢失。 直接那个工单后台就不可见了！

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by imrelax** [comment]
经过更加深入的测试发现，不仅是工单不正常，连订单也不正常，整个系统都有点不正常了，

**Comment by cedar2025** [comment]
我测试工单回复 https://google.com这样的消息并不会导致任何的系统异常，你可以给出能复线这个问题的具体步骤吗？
