### ISSUE TITLE
[Feature request] 订阅链接中的flag

### ISSUE THREAD

**Issue by Nanqian** [cedar2025/Xboard#105]
默认的订阅订阅链接好像是会自动获取UA然后过滤掉部分节点，但是很多时候会判断错误，像clash.meta，明明支持hy2但会被过滤掉，希望能增加一个不过滤任何节点的flag以适配所有客户端

**Comment by cedar2025** [comment]
你可以使用&flag=meta&types=all来下发所有类型节点

**Comment by Nanqian** [comment]
> 你可以使用&flag=meta&types=all来下发所有类型节点

感谢，解决了
