### ISSUE TITLE
[Feature request] Better support hysteria2's port hopping feature

### ISSUE THREAD

**Issue by PA733** [cedar2025/Xboard#110]
Please consider supporting the [naive port hopping feature](https://v2.hysteria.network/docs/advanced/Port-Hopping/) similar to [this commit](https://github.com/wyx2685/v2board/commit/27fcc978483701b906a845ec96c46632c9380369), rather than generating a single random port when creating configuration files.

**Comment by cedar2025** [comment]
is ok in this commit https://github.com/cedar2025/Xboard/commit/5a0e59b103657ccd300204046b877f653cd2aa30

**Comment by PA733** [comment]
Awesome!
This issue will be closed after tested.
Thanks a lot.

**Comment by PA733** [comment]
Tested, works well👍
