### ISSUE TITLE
[Feature request]多个域名时支付后跳转问题。

### ISSUE THREAD

**Issue by blackness3** [cedar2025/Xboard#118]
Please describe in detail the problems or needs you have encountered.
请详细描述你遇到的问题或需求。

当设置多个域名时支付后会自动跳转到后台设置的网址，如主页设置的是，123.com 

比如，再abc.com 支付后会自动跳转到123.com   ，

能否在支付后只返回当前支付的页面。

比如abc.com支付后返回 abc.com
或者提供个按钮，可返回主域或者返回当前

**Comment by imrelax** [comment]
是的。 。会有这个问题。

**Comment by blackness3** [comment]
看起来不是很好实现，因为如果前后分离了。跳转地址可能会是前端设置的api地址

// API地址
window.routerBase = 'https://1.2.3/'

**Comment by cedar2025** [comment]
https://github.com/cedar2025/Xboard/commit/8416381fa034a69df6d29c5e58dd64a770118a87 已经修复
