### ISSUE TITLE
[BUG] xrayr修改版后端 用grcp+TLS 发现面板不下发sni 

### ISSUE THREAD

**Issue by ZHQSM** [cedar2025/Xboard#12]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非XBoard问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-XBoard issues please go to the project side to ask questions

The XBoard version number you are using
当前使用的XBoard版本号
--------
最新版

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
xrayr修改版后端 用grcp+TLS 发现面板不下发sni  客户端是clash verge

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by cedar2025** [comment]
https://github.com/cedar2025/Xboard/commit/9939f2c2e1777b534caee284796c1b63efdd18bb
在这个commit中已经修复
