### ISSUE TITLE
[BUG]管理员"后台路径"更改功能不可用

### ISSUE THREAD

**Issue by FoamCold** [cedar2025/Xboard#125]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非XBoard问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-XBoard issues please go to the project side to ask questions

The XBoard version number you are using
当前使用的XBoard版本号
--------
使用1panel并根据教程搭建
机器是甲骨文arm
XBoard v1.0.0

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
管理员后台-安全-后台路径 更改成功后未生效不可访问
安装时随机的后台路径依旧可以访问后台并登录，且报错误请求失败
数据库查看v2_settings - secure_path已经为更改后的后台路径

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
![4195bc6e31c9b9dd0415b4b706a12594](https://github.com/cedar2025/Xboard/assets/139764186/a62f92f5-daf1-41bd-af6d-8073d4c3248c)

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------
docker的不会看

**Comment by cedar2025** [comment]
目前修改后需要重启才可以生效， 后面会优化一下这块的体验

**Comment by cedar2025** [comment]
docker compose restart 可以重启

**Comment by alexallen1** [comment]
建议强制提醒：{必须重启以便生效}
