### ISSUE TITLE
升级到fd52795 版本，报数据库错误

### ISSUE THREAD

**Issue by jelly0925** [cedar2025/Xboard#126]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非XBoard问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-XBoard issues please go to the project side to ask questions

The XBoard version number you are using
当前使用的XBoard版本号
[fd52795](https://github.com/cedar2025/Xboard/commit/fd52795f497e8a5bed153a03f27814ff36608947)

Briefly describe the problem you are experiencing
简单描述你遇到的问题
aapanel + Docker Compose版本升级报错

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
![xboard](https://github.com/cedar2025/Xboard/assets/3022023/54aedcb1-a3f3-4a3e-b682-cac83f5c8cb9)

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by cedar2025** [comment]
这个错误看起来是你的数据库连接失败了， 你需要自行检查一下相关的设置

**Comment by jelly0925** [comment]
> 这个错误看起来是你的数据库连接失败了， 你需要自行检查一下相关的设置

感谢，恢复了备份解决了。
