### ISSUE TITLE
[BUG]初始化失败

### ISSUE THREAD

**Issue by YangHaoNing-CN** [cedar2025/Xboard#134]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非XBoard问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-XBoard issues please go to the project side to ask questions

The XBoard version number you are using
当前使用的XBoard版本号
--------
不详

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
后台登录出现这个画面，前台提示初始化失败，crontab和supervisor日志看起来无报错，服务器重启过，依旧

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
![image](https://github.com/cedar2025/Xboard/assets/83169812/d01c728c-ef07-4472-8f37-b14722b97183)

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------
无日志

**Comment by Weoworks** [comment]
检查php组件中的redis是否处于运行中

**Comment by cedar2025** [comment]
提供数据库当中的v2_log 日志

**Comment by YangHaoNing-CN** [comment]
![image](https://github.com/cedar2025/Xboard/assets/83169812/047158ac-74bd-4d47-828d-c081d61c0348)
已解决

**Comment by alexallen1** [comment]
> 提供数据库当中的v2_log 日志
请问v2_log体积超过3G  怎么优化减小体积~
