### ISSUE TITLE
[BUG]邮件does not comply with addr-spec of RFC 2822.

### ISSUE THREAD

**Issue by YangHaoNing-CN** [cedar2025/Xboard#144]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非XBoard问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-XBoard issues please go to the project side to ask questions

The XBoard version number you are using
当前使用的XBoard版本号(git commit id)
--------
当日最新
Would you like to deploy using Docker?
你的部署方式（是否为Docker）
--------
aapanel+docker

Please briefly describe the issue you encountered (preferably with reproducible steps).
简单描述你遇到的问题（最好带上复现步骤）
--------
发送邮件时提示
阿里邮箱的文档https://help.aliyun.com/document_detail/36661.html?spm=a2c4g.36698.0.i5
由于本地不开放25，所以使用465

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

Run the php artisan log:export 7 command to export log files (where 7 represents logs for the last 7 days).
运行`php artisan log:export 7` 命令导出的日志文件(其中7为最近7天的日志)。
--------
docker运行

**Comment by p1145p** [comment]
发件地址是邮箱地址
你应该去查一下那个报错的

**Comment by YangHaoNing-CN** [comment]
resend解决了，谢谢
