### ISSUE TITLE
请问在哪里修改custom.clash.yaml

### ISSUE THREAD

**Issue by Ekko1048** [cedar2025/Xboard#147]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非XBoard问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-XBoard issues please go to the project side to ask questions

The XBoard version number you are using
当前使用的XBoard版本号(git commit id)
--------
1.0.0

Would you like to deploy using Docker?
你的部署方式（是否为Docker）
--------
1panel,Docker

Please briefly describe the issue you encountered (preferably with reproducible steps).
简单描述你遇到的问题（最好带上复现步骤）
--------
请问在哪里修改custom.clash.yaml

**Comment by Ekko1048** [comment]
> 1、项目目录新建resources/rules/custom.clash.yaml 2、修改docker-compose.yaml 文件中 services > xboard > volumes 增加
> 
> ```
> - resources/rules/custom.clash.yaml:/www/resources/rules/custom.clash.yaml 
> ```
> 
> 3、重启项目
> 
> ```
> docker compose down
> docker compose up -d
> ```

谢谢大佬，不过配置后没有生效，走的还是默认的yaml

**Comment by Ekko1048** [comment]
> 1、项目目录新建resources/rules/custom.clash.yaml 2、修改docker-compose.yaml 文件中 services > xboard > volumes 增加
> 
> ```
> - resources/rules/custom.clash.yaml:/www/resources/rules/custom.clash.yaml 
> ```
> 
> 3、重启项目
> 
> ```
> docker compose down
> docker compose up -d
> ```

搞定了
`- ./resources/rules/custom.clash.yaml:/www/resources/rules/custom.clash.yaml `

**Comment by liulisanwan** [comment]
佬，方便给下您的模板吗。原始的有些规则不全。我想跟subconverter项目一样生成多种规则。
