### ISSUE TITLE
请问一下报错 add users error: not have any user

### ISSUE THREAD

**Issue by hhttco** [cedar2025/Xboard#165]
请问一下 Run nodes failed" err="start node controller [https://xxxxx-hysteria2-1] error: add users error: not have any user 需要怎么处理。

**Comment by hhttco** [comment]
目前还没有解决，这个和面板机的内核有关系吗？我用的是 debian 10

**Comment by diyes** [comment]
我也遇到这样的问题
后面换了个协议 可以了
