### ISSUE TITLE
[BUG]面板的clash订阅用不了

### ISSUE THREAD

**Issue by ForNoonee** [cedar2025/Xboard#168]
直接使用面板的clash订阅导出无法使用；具体表现在只有第一个节点能导入，而且基本没法用。

**Comment by ForNoonee** [comment]
hy2节点目前好像也只有小火箭能导入。V2rayN要自己手动写。clash用不了

**Comment by Trpscc** [comment]
> hy2节点目前好像也只有小火箭能导入。V2rayN要自己手动写。clash用不了

使用Clashmeta /mihomo 内核的客户端可以导入，如：Clashmeta for android   Clash verage

**Comment by Trpscc** [comment]
> > hy2节点目前好像也只有小火箭能导入。V2rayN要自己手动写。clash用不了
> 
> 使用Clashmeta /mihomo 内核的客户端可以导入，如：Clashmeta for android Clash verage

原版clash 内核早停更了，不能支持很正常

**Comment by ForNoonee** [comment]
感谢，我发现是我这个面板用的是clash原版，换一下clashmeta就可以用了。但是我想问问怎么才能自定义面板生成的订阅方式，比如二维码，直接发订阅地址之类的。文件找不到

**Comment by dudukee** [comment]
麻烦请问自建的hy2节点，使用clashmeta直接订阅可以下载到yaml文件，浏览器里打开订阅地址没办法下载是什么原因？
