### ISSUE TITLE
v2bx无法获取用户[BUG]

### ISSUE THREAD

**Issue by g1024679424** [cedar2025/Xboard#173]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非XBoard问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-XBoard issues please go to the project side to ask questions

The XBoard version number you are using
当前使用的XBoard版本号(git commit id)
--------

Would you like to deploy using Docker?
你的部署方式（是否为Docker）
--------
是

Please briefly describe the issue you encountered (preferably with reproducible steps).
简单描述你遇到的问题（最好带上复现步骤）
--------
正常配置，服务器netcup的奥地利机子，凌晨的时候有时候可以获取，到了白天就一直无法获取，所以晚上配置好第二天就不行了
v2bx 配置好后无法获取用户  用的 vless reality

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
v2bx 返回的日志
Jul 13 07:19:15 laxl1-20240618001720128c68 V2bX[22077]: V2bX v0.0.9 (A V2board backend based on multi core)
Jul 13 07:19:16 laxl1-20240618001720128c68 V2bX[22077]: time="2024-07-13T07:19:16-04:00" level=error msg="Run nodes failed" err="start node controller [https://xxxxx.xyz-vless-3] error: add users error: not have any user"
Jul 13 07:19:16 laxl1-20240618001720128c68 systemd[1]: V2bX.service: Succeeded.

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

Run the php artisan log:export 7 command to export log files (where 7 represents logs for the last 7 days).
运行`php artisan log:export 7` 命令导出的日志文件(其中7为最近7天的日志)。
--------

**Comment by phoenixg** [comment]
Have you found a solution?

**Comment by g1024679424** [comment]
是的 你得保证有一个有效用户能使用套餐

**Comment by nts-truongson** [comment]
pls show step by step solve this issue
