### ISSUE TITLE
[Feature request]请问是否兼容V2Board前后分离部署的静态文件？谢谢！

### ISSUE THREAD

**Issue by codionx** [cedar2025/Xboard#18]
请问是否兼容V2Board前后分离部署的静态文件？谢谢！

**Comment by cedar2025** [comment]
兼容前后端分离的。

**Comment by codionx** [comment]
谢谢！我再试试。我迁移过来，竟然无法兼容。谢谢！

**Comment by cedar2025** [comment]
不，他是兼容的，在https://github.com/cedar2025/Xboard/commit/08c8f46eb3f64a6d32eb6c5e457ba9beb6ce52aa 这个commit之前如果你使用的是第三方的主题可能会导致无法正常工作的问题，请检查你是否是因为这个问题导致的无法正常使用。

**Comment by codionx** [comment]
OK. 谢谢。不过，看起来也不需要前后分离了。直接反向代理就好了。谢谢
