### ISSUE TITLE
[BUG]我用的一面具模块订阅节点的时候出现504的错误

### ISSUE THREAD

**Issue by wyUshio** [cedar2025/Xboard#183]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非XBoard问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-XBoard issues please go to the project side to ask questions

The XBoard version number you are using
当前使用的XBoard版本号(git commit id)
--------
最新版
Would you like to deploy using Docker?
你的部署方式（是否为Docker）
--------
用的1panel的部署方式

Please briefly describe the issue you encountered (preferably with reproducible steps).
简单描述你遇到的问题（最好带上复现步骤）
--------
用面具模块订阅节点出现504,路由器能正常请阅,我问模块开发者,告知是否加了奇奇怪怪的验证,问下各位遇到这样的问题要怎么修改配置?
之前用安装aaPanel没这方面的问题.求解决,谢谢
![屏幕截图 2024-06-16 081012](https://github.com/user-attachments/assets/c4658d73-bd2d-4845-b10a-cf4b69d2bc53)

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

Run the php artisan log:export 7 command to export log files (where 7 represents logs for the last 7 days).
运行`php artisan log:export 7` 命令导出的日志文件(其中7为最近7天的日志)。
--------

**Comment by wyUshio** [comment]
![photo_2024-07-25_17-07-10](https://github.com/user-attachments/assets/a720c359-05f7-4abd-8a44-7f780df42ddc)

**Comment by cedar2025** [comment]
感觉帮不到你。
