### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by yootus** [cedar2025/Xboard#21]
很多用户不知道去哪获取订阅。找不到一键订阅。。。
能否加个功能。把各个订阅直接展示在首页。
加个开关切换开启是否全展示在首页。

**Comment by yootus** [comment]
参考主题：https://ednovas.org/

**Comment by yootus** [comment]
主题github：https://github.com/krsunm/Aurora

**Comment by cedar2025** [comment]
暂时不会考虑增加。 默认主题参照原版主题的风格。
