### ISSUE TITLE
[Feature request]  是否会继续坚持 前后端分离？

### ISSUE THREAD

**Issue by imrelax** [cedar2025/Xboard#23]
Please describe in detail the problems or needs you have encountered.
请详细描述你遇到的问题或需求。
目前我再使用 前后端分离的方式 部署网站。这个对我挺实用的！！
Xboard 是否会继续支持这个 功能？

**Comment by cedar2025** [comment]
你可以继续坚持使用前后端分离的部署方式，这并不影响

**Comment by imrelax** [comment]
原版是 会更新前端版本的。比如有可能新功能增加，势必要修改前端。
那你这边后期如果功能更新。是否会分离前端出来呢？

**Comment by cedar2025** [comment]
是否分离前端都是个人运维上的选择， 我没有单独将前端作为一个仓库。但是你可以自行将前端抽离做前后端分离部署。
