### ISSUE TITLE
[BUG]后台设置的时候，不注意在安全设置里选择了一个什么按钮，就一直是403 Forbidden了，要怎么恢复？

### ISSUE THREAD

**Issue by davidGangGang** [cedar2025/Xboard#240]
Would you like to deploy using Docker?
你的部署方式（是否为Docker）
--------
Docker

**Comment by davidGangGang** [comment]
问题已解决，打开数据库，找到设置表，把安全模式设为0就行了

**Comment by zhaolu1206** [comment]
> 问题已解决，打开数据库，找到设置表，把安全模式设为0就行了
大佬，同样问题，如何解决？
