### ISSUE TITLE
有计划什么时候发布稳定版吗？

### ISSUE THREAD

**Issue by dayhi** [cedar2025/Xboard#26]

**Comment by cedar2025** [comment]
估计明年会发布稳定版

**Comment by dayhi** [comment]
> 估计明年会发布稳定版

这是一个很好的项目，他大量优化了程序的响应速度，非常感谢您能来源。

我准备从现在将这个项目发布到我的正式环境，来测试bug，并修复他并上传，我迫不及待想看到他正式上线。

同时我想加入开发队伍，修改一些小功能
例如：
- user端的公告栏能正常显示markdown
- 在admin界面直接通过ssh管理落地机

如果您或者您的团队同意的话，可以通过请通过邮箱联系我：fe67116578edff@crankymonkey.info


无论通过与否，预祝项目越来越好，同时看过后麻烦删除
