### ISSUE TITLE
升级操作不规范，导致无法显示流量统计和用户在线情况

### ISSUE THREAD

**Issue by riverfell** [cedar2025/Xboard#283]
1、部署xboard
2、把之前未知版本v2board的v2board db sql导出
3、xboard数据库导入v2board数据

在该操作后，xboard上看不到用户流量统计和用户在线情况，遂按照README手动对数据库做了迁移，情况依旧。

有没有大佬给个修复的方向，小弟不太懂php。感谢！

**Comment by cedar2025** [comment]
回滚旧版本吧

**Comment by cedar2025** [comment]
你用的节点后端是xrayr 还是 soga 呢

**Comment by riverfell** [comment]
> Referen

是xrayr呢

**Comment by riverfell** [comment]
换修改版xrayr解决了
