### ISSUE TITLE
[BUG]Hysteria设置的上下行速度无法出现在用户配置内

### ISSUE THREAD

**Issue by Xiaodu233** [cedar2025/Xboard#289]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非XBoard问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-XBoard issues please go to the project side to ask questions

The XBoard version number you are using
当前使用的XBoard版本号(git commit id)
--------
f86ccae

Would you like to deploy using Docker?
你的部署方式（是否为Docker）
--------
Docker

Please briefly describe the issue you encountered (preferably with reproducible steps).
简单描述你遇到的问题（最好带上复现步骤）
--------
Hysteria节点配置好上下行速度，客户端Sing-Box和Hiddify获取的配置内没有up_mbps和down_mbps两个字段。
已检查过客户端的UA，节点有填入上下行速度。

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
无

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
无

Run the php artisan log:export 7 command to export log files (where 7 represents logs for the last 7 days).
运行`php artisan log:export 7` 命令导出的日志文件(其中7为最近7天的日志)。
--------
无

**Comment by cedar2025** [comment]
https://github.com/cedar2025/Xboard/commit/de18cfe596ae3371d2591d7e874c495a32eec76a

已修复
