### ISSUE TITLE
[BUG]前端展示

### ISSUE THREAD

**Issue by MoeclubM** [cedar2025/Xboard#33]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非XBoard问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-XBoard issues please go to the project side to ask questions

The XBoard version number you are using
当前使用的XBoard版本号
1.0.0
--------

Briefly describe the problem you are experiencing
简单描述你遇到的问题 
套餐购买页面，原版未填写价格的套餐不开放购买 新ui会在周期位置显示错误
--------

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
![image](https://github.com/cedar2025/Xboard/assets/54182920/cfdd740b-d292-41c8-a4b9-2a88ac9e1cf7)

--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by cedar2025** [comment]
你应该选择一个周期填写价格，而不是填写任何数值。
