### ISSUE TITLE
[BUG] 根据《aapanel安装指南》安装，提示redis连接失败：Connection refused

### ISSUE THREAD

**Issue by djymike** [cedar2025/Xboard#38]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非XBoard问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-XBoard issues please go to the project side to ask questions

The XBoard version number you are using
当前使用的XBoard版本号
--------
Latest

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------

根据《aapanel安装指南》安装，提示需要输入redis配置，我都按照默认配置回车时，提示redis连接失败：Connection refused，
但之前已经在php8.1内安装了插件redis

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

![image](https://github.com/cedar2025/Xboard/assets/25447833/0ee4e948-510e-478c-8cc0-bb53a8981e30)

**Comment by djymike** [comment]
系统是debian11

**Comment by ZHQSM** [comment]
还需要重新单独安装一次redis 数据库

**Comment by djymike** [comment]
> 还需要重新单独安装一次redis 数据库
是要在app store中再安装一下吗

**Comment by djymike** [comment]
已解决，宝塔面板安装的redis在ovh debian11的环境中安装，无法自动启动，需要通过命令行启动
