### ISSUE TITLE
[BUG]更新订阅提示The remote server returned an error: (500) Internal Server Error

### ISSUE THREAD

**Issue by yao450** [cedar2025/Xboard#39]
更新订阅提示The remote server returned an error: (500) Internal Server Error

**Comment by yao450** [comment]
docker-compose部署，不知道是哪里的权限问题

**Comment by cedar2025** [comment]
你好请提供更多的细节， 例如后台节点配置，使用的客户端以及其版本信息等。

**Comment by systemadmin2024** [comment]
我也遇到了，用的是docker部署：https://github.com/cedar2025/Xboard/blob/dev/docs/aapanel+docker%E5%AE%89%E8%A3%85%E6%8C%87%E5%8D%97.md

pc端v2rayn，版本v6.33
安卓端v2rayng，版本v1.8.5
ios端小火箭，最新版本
订阅带有vless和Trojan的节点时就提示这个，换成vmess正常。

singbox正常，clash正常。圈x正常。

**Comment by cedar2025** [comment]
你尝试更新到最新版本试试，如果不行贴出你的节点配置看看

**Comment by zassen** [comment]
最后发现是修改custom.clash.yaml引起的。。

**Comment by Ekko1048** [comment]
> 我碰到了同样的问题，最后发现是修改custom.clash.yaml引起的。。

在哪里修改custom.clash.yaml，求指点
