### ISSUE TITLE
公告支持 html [Feature request]

### ISSUE THREAD

**Issue by FaithAluten** [cedar2025/Xboard#41]
Please describe in detail the problems or needs you have encountered.
请详细描述你遇到的问题或需求。

**Comment by owo10086** [comment]
支不支持，不会自己试试吗

**Comment by FaithAluten** [comment]
> 支不支持，不会自己试试吗

是看不懂Feature request什么意思么？

**Comment by cedar2025** [comment]
一直都支持HTML的
