### ISSUE TITLE
[BUG]VLESS+gRPC+TLS协议无法下发订阅

### ISSUE THREAD

**Issue by beijiwangluo** [cedar2025/Xboard#42]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非XBoard问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-XBoard issues please go to the project side to ask questions

The XBoard version number you are using
当前使用的XBoard版本号
--------
最新

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
VLESS+gRPC+TLS无法下发订阅

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

![IMG_20240103_125959_201](https://github.com/cedar2025/Xboard/assets/64509408/64f4e861-a807-4b2a-8411-a979bafe3764)

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by cedar2025** [comment]
https://github.com/cedar2025/Xboard/commit/3a4efcc1f8c91e3c81a0598457e13a4b90adf818

**Comment by ZHQSM** [comment]
还需将下面grpc 的代码也改成 server_name  才能解决
