### ISSUE TITLE
[Feature request]V2rayN支持hysteria2

### ISSUE THREAD

**Issue by liummingyuan** [cedar2025/Xboard#43]
是否可以支持hyseteria2下发

**Comment by owo10086** [comment]
这种不算反馈的问题，能不能进群问

**Comment by ishkong** [comment]
https://github.com/cedar2025/Xboard/pull/52
已经pr了，自测能用，等待大佬合并

**Comment by cedar2025** [comment]
已经合并了 https://github.com/cedar2025/Xboard/pull/52

感谢ishkong
