### ISSUE TITLE
[BUG]使用Docker-Compose部署 订阅无法更新的问题

### ISSUE THREAD

**Issue by Gogoworks** [cedar2025/Xboard#44]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非XBoard问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-XBoard issues please go to the project side to ask questions

The XBoard version number you are using
当前使用的XBoard版本号
--------
最新

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
**使用Docker-Compose部署, aapanel nginx反向代理域名,设置SSL证书,在客户端更新订阅时,客户端报错**

_**错误
errortryingtoconnect:远程主机强迫关闭了一个现有
的连接。（oserror10054）**_

客户端: Clash.Nyanpasu_1.4.2_x64-setup

使用IP+7001(端口),正常.

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

![image](https://github.com/cedar2025/Xboard/assets/127202447/d48dbc1a-71fb-4d97-a1c3-cd64ff97323d)

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by rebecca554owen** [comment]
在浏览器打开你的订阅地址看能否访问。

**Comment by Gogoworks** [comment]
> 在浏览器打开你的订阅地址看能否访问。

在浏览器中可以正常打开访问.

导入就报错
![image](https://github.com/cedar2025/Xboard/assets/127202447/cd641fbc-4f76-4d7b-9672-f661a066e009)
