### ISSUE TITLE
[BUG]  支持前后端分离吗？

### ISSUE THREAD

**Issue by imrelax** [cedar2025/Xboard#45]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非XBoard问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-XBoard issues please go to the project side to ask questions

The XBoard version number you are using
当前使用的XBoard版本号
--------
1.9.0

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------

我想要部署前后端分离。 前端放在 cloudflare page 之类的上？ 
之前是V2Board 的现在切换到 XBOARD之后 没有单独的 前端项目  直接套用 无法访问！！

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by alexallen1** [comment]
Xboard 只是前端，本意也是分离
