### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by qwerdfqaq1** [cedar2025/Xboard#59]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非XBoard问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-XBoard issues please go to the project side to ask questions

The XBoard version number you are using
当前使用的XBoard版本号
--------

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
init.sh: 行 5: 29834 段错误               php composer.phar install -vvv
PHP Warning:  require(/vendor/autoload.php): Failed to open stream: No such file or directory in /www/wwwroot//artisan on line 18

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by cedar2025** [comment]
请提供下机器的供应商，系统的版本等信息用于复现。

**Comment by rebecca554owen** [comment]
这个是Centos系统上对吧？换Debian12。

**Comment by shaoyingrui** [comment]
> 这个是Centos系统上对吧？换Debian12。

我centos 7 部署这个错误。换debian12 一样这个~~
