### ISSUE TITLE
数据库迁移失败

### ISSUE THREAD

**Issue by ccb6d** [cedar2025/Xboard#68]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非XBoard问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-XBoard issues please go to the project side to ask questions

The XBoard version number you are using
当前使用的XBoard版本号
--------
Xboard docker-compose latest

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
数据库为远程服务器上的mysql8.0，在清除数据库后导入过程中报错。

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
![123](https://github.com/cedar2025/Xboard/assets/82276584/f8a2938d-d23a-4b98-b29c-c475ec057421)

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by cedar2025** [comment]
或许你应该使用mysql5.7。
