### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 61743** [cedar2025/Xboard#70]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非XBoard问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-XBoard issues please go to the project side to ask questions

The XBoard version number you are using
当前使用的XBoard版本号
--------
0.1.9

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
从v2b 1.7.4迁移过来的 开启google人机注册验证了以后 做完验证注册不跳转

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
<img width="1146" alt="207111123" src="https://github.com/cedar2025/Xboard/assets/89735371/9ac9d429-c664-413d-9f46-be132008e9c6">

**Comment by cedar2025** [comment]
https://github.com/cedar2025/Xboard/commit/d63dc106b3059736fe20d9c5502febec10bd2f0c 已经修复

**Comment by 61743** [comment]
更新完最新版连人机验证对话框都打不开了 疑似是 http://www.recaptcha.net/ 的问题 浏览器访问打不开 
![tupian1](https://github.com/cedar2025/Xboard/assets/89735371/fcb16947-2cd0-4d4a-b232-a581866da604)
![图片2](https://github.com/cedar2025/Xboard/assets/89735371/5271344f-56c8-4a80-8be3-b590d0740ee8)
