### ISSUE TITLE
部署中的小bug

### ISSUE THREAD

**Issue by baixuanyou** [cedar2025/Xboard#77]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非XBoard问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-XBoard issues please go to the project side to ask questions

The XBoard version number you are using
当前使用的XBoard版本号
V1.00
--------

Briefly describe the problem you are experiencing
简单描述你遇到的问题\
1.用aapanel部署的时候，第八步的supervisor配置填写“ php artisan Horizon”这句话中，如果直接复制，会导致不明错误，如果手动输入的话就可以运行，请改正一下，谢谢
2.在运行 php artisan Horizon语句时，会报错“ ERROR  Command &quot;Horizon&quot; is ambiguous. Did you mean one of these?  ”
需要将H小写，错误就会消失，不知道是不是我的问题
--------

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by baixuanyou** [comment]
![1](https://github.com/cedar2025/Xboard/assets/70987638/b6b08afe-4c6d-4014-9ee2-d953c9c3e34d)

**Comment by ikun2020** [comment]
你是不是多复制了一个空格😉

**Comment by cedar2025** [comment]
第八步的supervisor配置中文档是小写，你怎么写成大写了
