### ISSUE TITLE
[BUG]V2rayN订阅无法导入特定类型vless

### ISSUE THREAD

**Issue by hunxi-tzq** [cedar2025/Xboard#78]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非XBoard问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-XBoard issues please go to the project side to ask questions

The XBoard version number you are using
[当前使用的XBoard版本号](image: ghcr.io/cedar2025/xboard:latest)
--------

Briefly describe the problem you are experiencing
我在添加vless IPV6节点后，使用v2rayN更新订阅，无法显示vless节点。
最终定位于APP/ProtoCols/V2rayN:buildVless，此方法最终拼接节点链接时，没有对节点IP进行IPV6检测，需要把IPV6地址放置在中括号内。
--------

**Comment by cedar2025** [comment]
有没有一种可能，你添加ipv6节点的时候把括号加进去
