### ISSUE TITLE
[Question] Why forcing subdomain direct?

### ISSUE THREAD

**Issue by JobberRT** [cedar2025/Xboard#80]
The XBoard version number you are using
--------
v0.1.9

Briefly describe the problem you are experiencing
--------
Why `XBoard` makes subdomain direct? I can't see advantage of this behavior.

For many webiste that using `Cloudflare` as their CDN, it's common that these sites are being `TCP Reset`. If using `DIRECT`, then it will be impossible to subsribe. And if not using `DIRECT`, at least you left us a spare to workaround. 

For example: Use another device as proxy server for the first subscription. After that(and no `DOMAIN,subdomain,DIRECT` rule), we can update the subscription base on the config we downloaded

https://github.com/cedar2025/Xboard/blob/3241ce618bfa554d9b3e062957bf4d8c02e71ce0/app/Protocols/ClashMeta.php#L81-L85

**Comment by hczjxhdyz** [comment]
If the network cannot connect to the subscriber, it will indeed cause inconvenience in updating subscriptions, but if DIRECT is not used, it will cause other problems.
For example:
1. Unable to obtain the user's IP to decide to issue the designated node
2. When switching to an unavailable node, updating the subscription will fail.

You should solve your problem yourself, for example
1. Change to a new domain name
2. Introspect and modify the protocol file to meet your needs

**Comment by cedar2025** [comment]
If the network cannot connect to the subscriber, it will indeed cause inconvenience in updating subscriptions, but if DIRECT is not used, it will cause other problems.
For example:

Unable to obtain the user's IP to decide to issue the designated node
When switching to an unavailable node, updating the subscription will fail.
You should solve your problem yourself, for example

Change to a new domain name
Introspect and modify the protocol file to meet your needs

**Comment by JobberRT** [comment]
> If the network cannot connect to the subscriber, it will indeed cause inconvenience in updating subscriptions, but if DIRECT is not used, it will cause other problems. For example:
> 
> Unable to obtain the user's IP to decide to issue the designated node无法获取用户的IP以决定是否发放指定节点 When switching to an unavailable node, updating the subscription will fail.切换到不可用节点时，更新订阅将失败。 You should solve your problem yourself, for example你应该自己解决问题，例如
> 
> Change to a new domain name Introspect and modify the protocol file to meet your needs

I see, XBoard add a new feature with different IP get different node. That's a point. I've already modified the Protocol file, thanks
