### ISSUE TITLE
[Feature request]能否添加对ipv6的监听

### ISSUE THREAD

**Issue by Domgur0** [cedar2025/Xboard#82]
Please describe in detail the problems or needs you have encountered.
请详细描述你遇到的问题或需求。
刚部署完，发现ipv6无法访问，查看端口发现没监听IPv6
![IMG_3595](https://github.com/cedar2025/Xboard/assets/130534195/a320a3dd-6468-43d8-bf9c-0a72c1536416)

**Comment by Rakau** [comment]
listen [::]:端口号

**Comment by Domgur0** [comment]
嗯嗯，这个我知道，我只是想原生就支持

**Comment by cookielb** [comment]
> listen [::]:端口号

是加在这里面吗？/Xboard/.docker/etc/nginx/http.d/default.conf
    listen 7001 default_server;
    listen [::]:7001 default_server;
我只有IPv6加了还是打不开，具体是哪里不对呢？

**Comment by Domgur0** [comment]
> > listen [::]:端口号
> 
> 是加在这里面吗？/Xboard/.docker/etc/nginx/http.d/default.conf listen 7001 default_server; listen [::]:7001 default_server; 我只有IPv6加了还是打不开，具体是哪里不对呢？

重启容器了吗，反正我是在系统的nginx，弄的端口转发+域名访问的

**Comment by cedar2025** [comment]
https://github.com/cedar2025/Xboard/commit/9241369cbb831539938acee616947d4dbdd791a1 已经添加
