### ISSUE TITLE
[BUG]recaptcha 可以正常进行验证，但是验证完后点注册就没反应了

### ISSUE THREAD

**Issue by xixi-furry** [cedar2025/Xboard#83]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非XBoard问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-XBoard issues please go to the project side to ask questions

The XBoard version number you are using
当前使用的XBoard版本号
--------
[d69517b](https://github.com/users/cedar2025/packages/container/xboard/184499511?tag=d69517b)

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
开启recaptcha后，无法注册，但是关掉后正常。

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
没有任何提示，f12里也没有

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by cedar2025** [comment]
https://github.com/cedar2025/Xboard/commit/d63dc106b3059736fe20d9c5502febec10bd2f0c 这个问题在这个commit已经修复
