### ISSUE TITLE
[BUG] SS 2022返回的密码有错，格式不对

### ISSUE THREAD

**Issue by abcskjowjeoj** [cedar2025/Xboard#87]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非XBoard问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-XBoard issues please go to the project side to ask questions

The XBoard version number you are using
当前使用的XBoard版本号
--------
目前最新代码

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------

ss 2022多用户的密码格式和之前版本的不一样，api还是返回的老的格式，是一个uuid

正确的SS密码格式参考这个：
  "outbounds": [
    {
      "protocol": "shadowsocks",
      "settings": {
        "servers": [
          {
            "address": "{{ host }}",
            "port": 1234,
            "method": "2022-blake3-aes-128-gcm",
            "password": "{{ server psk }}:{{ user psk }}"
          }

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------
03-07 23:17:36.267 I/GoLog   (27822): new core
03-07 23:17:36.268 I/GoLog   (27822): proxy/shadowsocks_2022: create method > decode key: illegal base64 data at input byte 8
03-07 23:17:36.268 D/com.v2ray.ang(27822): go.Universe$proxyerror: proxy/shadowsocks_2022: create method > decode key: illegal base64 data at input byte 8

**Comment by cedar2025** [comment]
https://github.com/cedar2025/Xboard/commit/fd52795f497e8a5bed153a03f27814ff36608947
