### ISSUE TITLE
[Feature request]请教客户端实现hysteria2端口跳跃功能

### ISSUE THREAD

**Issue by alexallen1** [cedar2025/Xboard#88]
Please describe in detail the problems or needs you have encountered.
请详细描述你遇到的问题或需求。

请教Hysteria2客户端支持一种特殊的多端口地址格式：
example.com:1234,5678,9012 
example.com:20000-50000

我看到'狗狗加速'的机场客户端自动Hysteria  20000-40000端口，
请问xboard如何实现~

**Comment by blackness3** [comment]
希望增加。

**Comment by blackness3** [comment]
目前应该是 在定义范围后，随机下发一个端口

**Comment by cedar2025** [comment]
已经添加 https://github.com/cedar2025/Xboard/commit/5a0e59b103657ccd300204046b877f653cd2aa30
