### ISSUE TITLE
[Feature request]功能增加,修复。

### ISSUE THREAD

**Issue by movecat** [cedar2025/Xboard#9]
1，AFF增加一项分享获得时间的选项，时间按天算。管理后台可以选者全局AFF是获得时间还是佣金。可以单独编辑某个用户获得获得时间或者跟随系统。
2，后台订单管理页面增加显示每条账单使用的支付通道，账单内容显示支付通道，手续费。现在的账单不显示手续费。
3，现在的货币好像只支持CNY，后台货币单位设置成USD，支付接口货币单位设置为USD，套餐设置为USD价格，例如：10USD，跳转到支付后还是显示10CNY。需要修复这个bug，可以支持在后台设置货币单位和支付接口货币单位后，直接能按设置的货币来收费。

**Comment by cedar2025** [comment]
业务上的功能暂时不会考虑增加， 支付的问题你可以提供更多的信息，有可能是支付商那边并不支持指定货币的付款方式，需要参考支付商的文档
