### ISSUE TITLE
[Feature request]前端

### ISSUE THREAD

**Issue by Coffee-kitten** [cedar2025/Xboard#91]
Please describe in detail the problems or needs you have encountered.
请详细描述你遇到的问题或需求。
作者能提供build前的前端吗

**Comment by cedar2025** [comment]
感谢您对我们项目的兴趣和支持！我很高兴您对前端代码有兴趣。

目前，前端代码是项目的一部分，我们选择不公开原始（build前）的代码。这种决定是基于多种考虑，包括但不限于：保护知识产权、安全性考虑、以及确保代码库的整洁。

尽管如此，我们非常欢迎社区成员对项目的任何反馈和建议。如果您在使用编译后的版本时遇到问题，或者有特定的功能请求或改进建议，我非常希望听到。我们致力于不断改进，并且高度重视社区的贡献和反馈。

同时，如果未来我们改变策略决定开放更多代码，我们将确保在项目的更新中通知社区成员。

再次感谢您的理解和支持！
